const reverseKey = {
    "F1": "A",
    "I1": "B",
    "L1": "C",
    "N1": "D",
    "P1": "E",
    "T1": "F",
    "U1": "G",
    "V1": "H",
    "W1": "I",
    "X1": "J",
    "Y1": "K",
    "Z1": "L",
    "F2": "M",
    "I2": "N",
    "L2": "O",
    "N2": "P",
    "P2": "Q",
    "T2": "R",
    "U2": "S",
    "V2": "T",
    "W2": "U",
    "X2": "V",
    "Y2": "W",
    "Z2": "X",
    "F3": "Y",
    "I3": "Z",
    ",": ",",
    " ": " ",
    ".": "."
}

export default reverseKey;